# Generated by Django 5.1.1 on 2024-09-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='img',
            field=models.ImageField(default=1, upload_to='cars/'),
            preserve_default=False,
        ),
    ]
