# Generated by Django 5.1.1 on 2024-10-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_devos_remove_cars_price_alter_cars_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carsdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='Devos/')),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Featuresdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='Devos/')),
            ],
        ),
    ]
