# Generated by Django 5.1.1 on 2024-11-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_carsdetail_featuresdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='img',
            field=models.ImageField(upload_to='cars/'),
        ),
        migrations.AlterField(
            model_name='devos',
            name='img',
            field=models.ImageField(upload_to='devos/'),
        ),
        migrations.AlterField(
            model_name='features',
            name='img',
            field=models.ImageField(upload_to='features/'),
        ),
    ]
